global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "dip-monitor"
    environment: "development"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"

  # DIP Services metrics
  - job_name: "dip-services"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      # Ingestion Service
      - targets: ["host.docker.internal:9090"]
        labels:
          service: "ingestion"
          tier: "api"

      # Classifier Service
      - targets: ["host.docker.internal:9091"]
        labels:
          service: "classifier"
          tier: "processing"

      # Routing Service
      - targets: ["host.docker.internal:9092"]
        labels:
          service: "routing"
          tier: "processing"

      # Response Service
      - targets: ["host.docker.internal:9093"]
        labels:
          service: "response"
          tier: "processing"

  # Kafka Exporter (if added)
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
        labels:
          service: "kafka"
          tier: "infrastructure"

  # PostgreSQL Exporter (if added)
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgresql"
          tier: "infrastructure"

  # Redis Exporter (if added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: "redis"
          tier: "infrastructure"

# Service discovery for dynamic targets
# Can be extended with Consul, Kubernetes, or file-based discovery
